LabWrok48/WepApp/Pages/Details.cshtml.cs
using ApiServices.Models;
using ApiServices.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class DetailsModel(GamesService service) : PageModel
    {
        private readonly GamesService _service = service;

        public Game? Game { get; set; }

        public void OnGet(int id)
        {
            try
            {
                Game = _service.GetGameByIdAsync(id).Result;
            }
            catch (Exception)
            {
            }
        }

        public async Task<IActionResult> OnPostUpdate(int id, string title, string publicationYear, string description, string price)
        {
            Game = new()
            {
                Id = id,
                Title = title,
                Description = description.Length > 0 ? description : null,
                Price = double.Parse(price),
                PublicationYear = short.Parse(publicationYear)
            };
            await _service.UpdateGameAsync(Game);
            return RedirectToPage("/Details", new { id });
        }
    }
}

LabWrok48/WepApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WepApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

LabWrok48/WepApp/Pages/Index.cshtml.cs
using ApiServices.Models;
using ApiServices.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WepApp.Pages
{
    public class IndexModel(GamesService service) : PageModel
    {
        private readonly GamesService _service = service;

        public IEnumerable<Game> Games;

        public async Task OnGet()
        {
            try
            {
                Games = await _service.GetGamesAsync();
            }
            catch (Exception)
            {
                Games = new List<Game>();
            }
        }

        public IActionResult OnPostDetails(int id)
        {
            return RedirectToPage("./Details", new { id });
        }

        public async Task OnPostDeleteAsync(int id)
        {
            try
            {
                await _service.DeleteGameAsync(id);
                RedirectToPage();
            }
            catch (Exception)
            {
                RedirectToPage();
            }
        }
    }
}

LabWrok48/WepApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WepApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

LabWrok48/WepApp/Pages/Details.cshtml
@page "{id}"
@model WebApp.Pages.DetailsModel
@{
}

<div>
    @if (Model.Game is not null)
    {
        <form asp-page-handler="Update">
            <input type="hidden" name="id" value="@Model.Game.Id"/>
            <p>Название: <input type="text" name="title" value="@Model.Game.Title" /></p>
            <p>Год выпуска: <input type="text" name="publicationYear" value="@Model.Game.PublicationYear" /></p>
            <p>Стоимость: <input type="text" name="price" value="@Model.Game.Price" /></p>
            <p>Описание: <input type="text" name="description" value="@Model.Game.Description" /></p>
            <button type="submit">Сохранить</button>
        </form>
    }
    else
    {
        <p>Игра не была найдена.</p>
    }
</div>

LabWrok48/WepApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h1>Список игр</h1>
<table>
    <thead>
        <tr>
            <th>Название</th>
            <th>Цена</th>
            <th>Подробнее</th>
            <th>Удалить</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var game in Model.Games)
        {
            <tr>
                <td>@game.Title</td>
                <td>@game.Price</td>
                <td>
                    <form asp-page-handler="Details">
                        <input type="hidden" name="id" value="@game.Id" />
                        <button type="submit" class="btn btn-primary">Подробнее</button>
                    </form>
                </td>
                <td>
                    <form asp-page-handler="Delete">
                        <button type="submit" class="btn btn-primary" asp-route-id="@game.Id">Удалить</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

LabWrok48/WepApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WepApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WepApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">WepApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - WepApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>